### ISSUE TITLE
Claiming Rewards on L&E it's not fixed

### ISSUE THREAD

**Issue by Marianavpt** [impactMarket/support-issues#12]
| name: Nicky
| phone: 0700989944
| email: [girlsinitiative2020@gmail.com](mailto:girlsinitiative2020@gmail.com)
| address: 0x3188F53c13A35F513dcb47386Be88239B86c3B81
| role: Community Manager| gerente de comunidad| gestionnaire de communauté| gestor de comunidade
| issue: Libera
| issue2: Learn&amp;Earn| Aprende&amp;gana| Apprendre&amp;Gagner| Aprender&amp;Ganhar

> We cant claim our rewards.  I have the latest version of libera

**Comment by obernardovieira** [comment]
can they share a screenshot with the version? This is wallet related, I've removed the tag to Paulo.

**Comment by Marianavpt** [comment]
Paulo just told me this issue was related with lack of funds on the contract. Is that it? do you still need the screenshot?

**Comment by Marianavpt** [comment]
is this issue fixed now @obernardovieira ?

**Comment by vibern0** [comment]
Yes, you can close this since the issue right now is the lack of funds. We did fund the level again but the funds were quickly claimed. It's Jessica who's tracking the amount allocated, so we need to wait to be sure we won't send more than the allocated values. Once that limited of the allocated amount is reached, the course will still be available, but no new rewards.
